### ISSUE TITLE
ayyyy, 1.x, nice

### ISSUE THREAD

**Issue by aegershman** [kubernetes-sigs/minibroker#109]
nice 👍 great stuff. that's all. no issue.

thanks for all the time and energy and advocacy folks put into minibroker, OSBAPI, service bindings, and everything that goes into it. please forgive the issue spam, I'm not sure if there's a slack or anything, i'm kind of being lazy by not looking for it, but-- 

regardless, just wanted to say thanks 👍

**Comment by f0rmiga** [comment]
Thanks for the kind message, @aaroniscode!
Minibroker is under the Service Catalog SIG, so we are at the #sig-service-catalog channel on the Kubernetes Slack.
It was a pleasure to push Minibroker forward so far. I hope you find 1.0 helpful with the improvements. :)
