### ISSUE TITLE
Support installing minibroker in a namespace

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/minibroker#11]
Our helm chart assumes installing as a ClusterServiceBroker. I think that will need to be configurable, maybe with a flag like `clusterScoped` and then also if I install multiple brokers the rbac config shouldn't collide.

**Comment by zulandar** [comment]
/dibs going to review and see what I come up with.

**Comment by f0rmiga** [comment]
@zulandar Have you ever had a chance to look at this? I recently implemented some changes to rbac. Now, we support a _namespaced_ mode in which we whitelist namespaces and only bind minibroker to a ClusterRole that allows `get` and `list` on `namespaces`. Other than that, everything _should_ be namespaced.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs.
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
