### ISSUE TITLE
Update chart repository URL to new location

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/minibroker#115]
Helm is losing their old chart repository location and have had to move to a new URL. We should update our hard-coded URL for the stable repository to the new location:

OLD: https://kubernetes-charts.storage.googleapis.com/ 
NEW: https://charts.helm.sh/stable

Announcement here: https://helm.sh/blog/new-location-stable-incubator-charts/

**Comment by f0rmiga** [comment]
Thanks for fixing this @Evalle! :)
