### ISSUE TITLE
ARM64/aarch64 image

### ISSUE THREAD

**Issue by jiayihu** [kubernetes-sigs/minibroker#120]
Would be possible to have an image for the ARM64/aarch64 arch? service-catalog has support for it with the image `https://quay.io/repository/kubernetes-service-catalog/service-catalog-arm64?tag=v0.3.1&tab=tags`, it would be nice if you could also add the ARM target.

Thanks.

**Comment by f0rmiga** [comment]
Hi @jiayihu! It would indeed be nice to have an ARM image. This is not a top priority, though. I'd love to accept PRs for it!

**Comment by jiayihu** [comment]
I'd love to but I have zero knowledge in Go, especially cross-compiling, for the time being 😄 Maybe in the next future, I feel pretty much obliged to learn it if I want to continue studying k8s.

In the meantime, I'll leave the honour to someone else and I'm using both [ups-broker](https://github.com/kubernetes-sigs/service-catalog/tree/master/charts/ups-broker), which has an ARM image, and a custom Rust-written OSB.
