### ISSUE TITLE
Uninstalling minibroker should remove any resources created by minibroker

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/minibroker#2]
Right now the helm releases, and the minibroker configmaps remain after uninstalling.

**Comment by f0rmiga** [comment]
@carolynvs Should we use the Helm hooks for this?

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs.
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
