### ISSUE TITLE
Allow relative urls in index.yaml

### ISSUE THREAD

**Issue by sebastien-prudhomme** [kubernetes-sigs/minibroker#21]
Hi, since Helm 2.5.0, it's possible to use relative urls in index.yaml chart repository: https://github.com/helm/helm/blob/master/docs/chart_repository_faq.md

Minibroker is not compatible with that mode.

In `pkg/helm/helm.go`, the `LoadChart` function should first check if chartURL is a fully qualified URL, if not, build an URL with the relative URL and "repoURL".

**Comment by carolynvs** [comment]
Cool! Let me know if you are interested in working on it too. Otherwise, this is up for grabs for anyone who'd like a good first PR.

**Comment by KamalSinghKhanna** [comment]
hey! I am new here would like to work on this issue.  please guide me how to get started?

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs.
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
