### ISSUE TITLE
Broken link in readme.md

### ISSUE THREAD

**Issue by agracey** [kubernetes-sigs/minibroker#23]
The link for "Service Catalog CLI (svcat)" to https://github.com/osbkit/minibroker#requirements is broken. 

I'm guessing it should link to here instead?
https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/install.md#installing-the-service-catalog-cli

**Comment by zulandar** [comment]
Submitted PR to update the readme.md

**Comment by zulandar** [comment]
Fixed in PR. @carolynvs this issue can be closed out now.

**Comment by carolynvs** [comment]
Fixed in #32
