### ISSUE TITLE
Adding Minio as one of the default service in minibroker too

### ISSUE THREAD

**Issue by gitricko** [kubernetes-sigs/minibroker#233]
Knowing there you can install Minio via Helm Charts 
`helm install stable/minio --name=minio --set accessKey=myaccesskey,secretKey=mysecretkey`

Why not add minio as part of the default services like postgres etc

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs.
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
