### ISSUE TITLE
Is this project in use by anyone?

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-sigs/minibroker#256]
At this time, the kubernetes project is considering archiving this project. It may still be forked and maintained externally, however there does not appear to be enough momentum in project to keep it going.

If you are a user of this project, please chime in on this thread.

**Comment by f0rmiga** [comment]
@mrbobbytables I think it would make sense to move this project to the Cloud Foundry Foundation, given the OSBAPI is already governed by CFF. https://www.openservicebrokerapi.org/governance

**Comment by mrbobbytables** [comment]
@f0rmiga happy to have that discussion. IIRC in past instances where this has occurred  - K8s has archived the project, but updated readme's / links to point to an "official" fork.

**Comment by f0rmiga** [comment]
@mrbobbytables Let's just archive the project, then. If anyone cares, the project can still be forked and maintained somewhere else. We can always update the README at a later time too.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs.
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
