### ISSUE TITLE
Helm chart and include a securityContext that includes runAsUser: 0

### ISSUE THREAD

**Issue by troytop** [kubernetes-sigs/minibroker#39]
The minibroker chart assumes that all PSPs allow you to run as root. Kubernetes will attempt to validate the pod spec against each available PSP in alphabetical order and choose the first PSP that validates the spec.

The pod spec is supposed to list all required privileges in a securityContext. The minibroker doesn't specify that it intends to run as root, so it validates against the the first PSP that validates the spec, but when it tries to run under a more restrictive PSP, it is not allowed to do so.

One way to fix this would be to modify the minibroker chart and include a securityContext that includes `runAsUser: 0`, so the pod would no longer validate against a PSP that does not allow running as root.

**Comment by troytop** [comment]
Adding the following to `templates/deployment.yaml` fixes the issue for me:

`      
    securityContext:
        runAsUser: 0
`

**Comment by troytop** [comment]
... but maybe the real fix is to use `MustRunAsNonRoot` and uncomment these two lines in the Dockerfile:

https://github.com/kubernetes-sigs/minibroker/blob/master/image/Dockerfile#L29

**Comment by f0rmiga** [comment]
> ... but maybe the real fix is to use `MustRunAsNonRoot` and uncomment these two lines in the Dockerfile:
> 
> https://github.com/kubernetes-sigs/minibroker/blob/master/image/Dockerfile#L29

The permanent link to the referred lines:
https://github.com/kubernetes-sigs/minibroker/blob/2800c6b4dab59c6bba3a5daa316f981d4dbb6e35/image/Dockerfile#L64-L65

**Comment by f0rmiga** [comment]
Since we want to keep avoiding any Docker `RUN` instructions on the final image (because of being able to build from `scratch`), we should add a file to the repository and just `COPY` it to the final image layer under `/etc/passwd`. Something like:

```
root:x:0:0:root:/root:/bin/bash
minibroker:x:1000:1000::/home/minibroker:/bin/bash
```

The `/home/minibroker` will need to be an ephemeral volume (or perhaps just `/home/minibroker/.cache`. This is because we want to also make the root filesystem read-only.
