### ISSUE TITLE
question: Can minibroker work without tiller ?

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes-sigs/minibroker#43]
## Question

Can minibroker work without tiller  and been installed using helm 3 ?

**Comment by carolynvs** [comment]
People are working on that but at the moment it only works with tiller.

**Comment by f0rmiga** [comment]
Currently, you can install Minibroker itself with Helm 3 while the internals is still using Tiller. Updating the internals is one of my next backlog items. :)

**Comment by f0rmiga** [comment]
@cmoulliard PR #72 should get rid of Tiller completely once it gets merged.
