### ISSUE TITLE
Cluster domain hard coded

### ISSUE THREAD

**Issue by mook-as** [kubernetes-sigs/minibroker#45]
in [`minibroker.buildHostFromService()`](https://github.com/kubernetes-sigs/minibroker/blob/cc75ae6bbec6c2b2a1f2edb3686e6938206bc8a3/pkg/minibroker/provider.go#L70) we hard code the cluster domain to `.cluster.local`; this may not be true for all clusters, and should probably be using some knob in the helm chart instead.

**Comment by f0rmiga** [comment]
/kind bug

There's also: https://github.com/kubernetes-sigs/minibroker/blob/24ebf5135474bdea42b50fc888fba096db2134d5/charts/minibroker/templates/broker.yaml#L9

**Comment by f0rmiga** [comment]
We may be able to get away with just removing `.cluster.local` and letting the in-cluster DNS do the magic.
