### ISSUE TITLE
Follow up on the context.TODO() items from #72

### ISSUE THREAD

**Issue by f0rmiga** [kubernetes-sigs/minibroker#77]
PR #72 introduced lots of `context.TODO()`. This was due to the bumping of the k8s libraries.
Minibroker must create proper contexts and pass them around with the requests. It will also enable future timeout implementations and tracing.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs.
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
