### ISSUE TITLE
Use port 443 when TLS is enabled

### ISSUE THREAD

**Issue by f0rmiga** [kubernetes-sigs/minibroker#79]
Currently, the service only uses port 80. When TLS is enabled, it should use port 443.

https://github.com/kubernetes-sigs/minibroker/blob/36e18250ef2c154490e8410ab5904c7ce42a159c/charts/minibroker/templates/service.yaml#L12

**Comment by jhvhs** [comment]
This has been fixed in the `master` branch by extracting the post as a variable:
https://github.com/kubernetes-sigs/minibroker/blob/master/charts/minibroker/templates/service.yaml#L12

**Comment by f0rmiga** [comment]
@jhvhs thanks for pointing it out. I'll close this issue for now, and maybe we can revisit in the future if we want to do a fancier check and get thinks more automatic.
(Ignore the bot, it got crazy) 😂
